In [1]:
%%spark
--conf spark.jars.packages=com.microsoft.ml.spark:mmlspark_2.11:0.18.1
--conf spark.jars.ivySettings=/home/sankuai/.m2/ivysettings.xml
--conf spark.yarn.queue=root.zw03.hadoop-jiulvalgo.etl
--conf spark.executor.cores=4
--conf spark.task.cpus=4

CmdOutput(['tail', '-50', '/home/sankuai/logs/spark-1783929219.log'], 2)

Warning: Ignoring non-Spark config property: mtjupyter.secret

:: loading settings :: file = /home/sankuai/.m2/ivysettings.xml

Ivy Default Cache set to: /home/sankuai/.ivy2/cache
The jars for the packages stored in: /home/sankuai/.ivy2/jars
:: loading settings :: url = jar:file:/opt/meituan/spark-3.0/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.microsoft.ml.spark#mmlspark_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-d8fa766a-bfc8-4fff-ba5c-1ac0edb33a07;1.0
	confs: [default]
	found com.microsoft.ml.spark#mmlspark_2.11;0.18.1 in mtdp
	found org.scalactic#scalactic_2.11;3.0.5 in mtdp
	found org.scala-lang#scala-reflect;2.11.12 in mtdp
	found org.scalatest#scalatest_2.11;3.0.5 in mtdp
	found org.scala-lang.modules#scala-xml_2.11;1.0.6 in mtdp
	found io.spray#spray-json_2.11;1.3.2 in mtdp
	found com.microsoft.cntk#cntk;2.4 in mtdp
	found org.openpnp#opencv;3.2.0-1 in mtdp
	found com.jcraft#jsch;0.1.54 in mtdp
	found org.apache.httpcomponents#httpclient;4.5.6 in mtdp
	found org.apache.httpcomponents#httpcore;4.4.10 in mtdp
	found commons-logging#commons-logging;1.2 in mtdp
	found commons-codec#commons-codec;1.10 in mtdp
	found com.microsoft.ml.lightgbm#lightgbmlib;2.2.350 in mtdp
	found com.github.vowpalwabbit#vw-jni;8.7.0.2 in mtdp
:: resolution report :: resolve 1686ms :: artifacts dl 4ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   15  |   2   |   2   |   0   ||   15  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: ERRORS
	unknown resolver null


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
:: retrieving :: org.apache.spark#spark-submit-parent-d8fa766a-bfc8-4fff-ba5c-1ac0edb33a07
	confs: [default]
	0 artifacts copied, 15 already retrieved (0kB/5ms)
SLA info url: http://cantor.data.sankuai.com/api/v1/task/normal_spark_luyiwei03_c1de576f/level
SLA info result: {
  "data": {
    "level": 0,
    "taskWeight": ""
  },
  "success": true
}

RSS config url: http://themis.data.sankuai.com/api/v2/spark/rss/whitelist/config/train/normal_spark_luyiwei03_c1de576f
RSS config from Themis: {
  "success" : false,
  "appName" : "normal_spark_luyiwei03_c1de576f",
  "arguments" : null,
  "enabled" : false
}
get RSS Cluster Conf url: http://themis.data.sankuai.com/api/spark/rss/cluster/config/zw03
RSS Cluster Conf: {
  "cluster" : "zw03",
  "disabled" : false
}
getExtraConf info url: http://themis.data.sankuai.com/api/spark/whitelist/config/etl/normal_spark_luyiwei03_c1de576f
getExtraConf info result: {
  "success" : false,
  "appName" : "normal_spark_luyiwei03_c1de576f",
  "arguments" : null,
  "enabled" : false
}
set spark.reducer.maxReqsInFlight to value: 10
set spark.reducer.maxBlocksInFlightPerAddress to value : 1
Invalid cantor schedulejobid: [None]

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json, joblib
import os, subprocess
import optuna

import lightgbm as lgb
import xgboost as xgb
from lightgbm import early_stopping, log_evaluation
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV, GridSearchCV
from sklearn.metrics import make_scorer, roc_auc_score, classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, log_loss
from sklearn.isotonic import IsotonicRegression

from pyspark.sql import functions as F
from pyspark.sql.functions import expr, when, col, udf, avg, lit, row_number
from pyspark.sql.types import DoubleType
from pyspark.sql.window import Window

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)

In [3]:
%%sql df --preview --quiet

SELECT a.*,b.intention
FROM mart_jiulv_flow.dws_stp_session_comp_df a
left join mart_hoteldim.stp_test_session_v2 b
on a.session_id = b.session_id
where a.dt between 20260301 and 20260630

/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series

                                             session_id  holiday_weekend_vacation_checkin_datekey_cnt  holiday_checkin_datekey_cnt  weekend_checkin_datekey_cnt  vacation_checkin_datekey_cnt  lead_time  checkin_datekey_cnt  goods_cnt  poi_cnt  aoi_cnt  city_cnt  stay_time  search_page_cnt  search_page_time  poi_list_cnt  poi_list_time  poi_info_cnt  poi_info_time  room_list_cnt  room_list_time  room_info_cnt  room_info_time  create_order_cnt  create_order_time  evaluate_page_cnt  evaluate_page_time  search_scenic_cnt  waitou_cnt  rednote_cnt  order_cnt  star2_cnt  star3_cnt  star4_cnt  star5_cnt  budget_cnt  express_cnt  business_cnt  theme_cnt  couple_cnt  apartment_cnt  inn_cnt  homestay_cnt  hostel_cnt  farmstay_cnt  family_guesthouse_cnt  guesthouse_cnt  resort_hotel_cnt  villa_cnt  family_cnt  esports_cnt  scarce_cnt  unique_cnt  lowprice_cnt  good_cnt  tourism_core_city_cnt  tourism_big_city_cnt  tourism_seasonal_city_cnt  tier1_city_cnt  new_tier1_city_cnt  tier2_city_cnt  tier3_city_cnt  tier4_city_cnt  tier5_city_cnt  university_cnt  transportation_hub_cnt  scenic_area_cnt  hospital_cnt  performance_sports_venue_cnt  convention_center_cnt  industrial_park_cnt  king_room_cnt  single_room_cnt  double_room_cnt  triple_room_cnt  suite_cnt  standalone_cnt  dorm_cnt  is_college_student  is_adult_single  is_adult_married_no_kids  is_adult_married_with_kids  is_over_60  is_senior  is_middle_age  is_young  is_minor  is_high_value  is_mid_value  is_low_value  is_l4  is_l1_3  is_youth_campus  is_business_elite  is_self_social  is_practical_life  is_family_guardian  is_vital_soldier  is_quality_visitor  is_kid_explorer  is_occasional_traveler  holiday_rnt_pct  travel_distance  is_holiday_weekend_vacation  is_holiday  is_weekend  is_vacation  order_lead_time  is_star2  is_star3  is_star4  is_star5  is_budget  is_express  is_business  is_theme  is_couple  is_apartment  is_inn  is_homestay  is_hostel  is_farmstay  is_family_guesthouse  is_guesthouse  is_resort_hotel  is_villa  is_family  is_esports  is_scarce  is_unique  is_lowprice  is_good  order_travel_distance  is_search_scenic  is_waitou  is_rednote  is_tourism_core_city  is_tourism_big_city  is_tourism_seasonal_city  is_tier1_city  is_new_tier1_city  is_tier2_city  is_tier3_city  is_tier4_city  is_tier5_city  is_university  is_transportation_hub  is_scenic_area  is_hospital  is_performance_sports_venue  is_convention_center  is_industrial_park  is_king_room  is_single_room  is_double_room  is_triple_room  is_suite  is_standalone  is_dorm  search_cnt  travel_session_cnt  is_search  is_travel_session  session_cnt  event_cnt  advance_checkin_datekey_cnt  sameday_checkin_datekey_cnt  overnight_checkin_datekey_cnt        dt  intention
0  0004d9c2-d945-4555-bb2b-3ed4cb40dffe1774328469906206                                             0                            0                            0                             0   1.968586                    3         10       33        5         2   2016.590               10           192.233            81       1012.949            55        518.295              0             0.0              0             0.0                 5              0.000                  0                 0.0                  0           0            0          7         89          4          0          0          66            2             2          1           0              5        0             3           0             0                      0               0                 0          0           2            0           0           2            88        79                      0                    93                          0              92                   1               0               0               0               0              70                       0               22            91                            69                      0                    0             34                0                3                0          0               0         0                   0                0                         0                           1           0          0              0         1         0              1             0             0      1        0              0.0                0.0             0.0                0.0                 0.0               0.0                 0.0              1.0                     0.0         0.428571       671.340350                            0           0           0            0              2.0         0         0         0         1          0           0            0         0          0             0       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 1          1         668                     0                    1                         0              1                  0              0              0              0              0              0                      0               1            1                            0                     0                   0             1               0               0               0         0              0        0          67                   0          1                  0            5        235                            1                            2                              0  20260324        NaN
1  0013B6F7-9F93-474A-AE7F-9EE4732608161774322092873217                                             1                            0                            1                             0   0.768868                    4         20       19        4         2   2139.327                3           674.675            65        655.400            83        508.624              0             0.0              0             0.0                 8             32.564                  0                 0.0                  0         181            0          5         90         20          3          4          32           49             9          0           0             11        0            12           0             0                      0               0                 4          0          11            8           4          17            70        82                      0                    27                          0               0                  27               0              90               0               0              90                       3                3            24                             0                      0                    0             10                4                8                4          0               0         0                   0                0                         0                           1           0          0              1         0         0              1             0             0      1        0              0.0                1.0             0.0                0.0                 0.0               0.0                 0.0              0.0                     0.0         0.024060        28.780815                            0           0           0            0              0.0         0         1         0         1          0           0            0         0          1             0       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 0          0          28                     0                    0                         0              0                  0              0              1              0              0              1                      0               0            0                            0                     0                   0             1               0               0               0         0              0        0         109                   0          1                  0           11        226                            2                            4                              0  20260324        NaN
2  001B52C0-649D-4B69-95A4-EF1B6CCF44B71774308721889368                                             0                            0                            0                             0   4.908046                    2          4       16       10         2    795.935               10           238.896            34        264.949            23        146.796              0             0.0              0             0.0                 3             12.991                  0                 0.0                  0         100           45          0         18          3          3          3           5            0            10          0           0              9        0             0           0             0                      0               0                 0          0           4            1           1           3            23        27                      0                    18                          9              18                   0               0               0               9               0              13                      12                7             0                             6                      2                    3              4                0                0                0          0               0         0                   0                0                         0                           0           0          0              0         0         1              1             0             0      1        0              0.0                0.0             0.0                0.0                 0.0               1.0                 0.0              0.0                     0.0         0.125000       150.878609                            0           0           0            0              NaN         0         0         0         0          0           0            0         0          0             0       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 0          0           0                     0                    0                         0              0                  0              0              0              0              0              0                      0               0            0                            0                     0                   0             0               0               0               0         0              0        0          14                   0          0                  0            5        102                            2                            1                              0  20260324        NaN
3   003426A5-4E99-4288-B22A-60213A15006A177435461003496                                             0                            0                            0                             0   4.929577                    2         26       35       16         1   1817.184                1             7.418            40        720.682           119        676.060              0             0.0              0             0.0                38            213.493                  0                 0.0                  0         230            0          2         74         57         23         12          28            0            82         41           0              6        0             0           0             0                      0               0                 9          0          42           66          54         110             2       163                      0                   166                          0               0                 166               0               0               0               0              26                       3               68            42                             0                     20                    0             21                0                2                0          0               0         0                   0                0                         0                           1           0          0              0         1         0              1             0             0      0        1              0.0                0.0             0.0                0.0                 1.0               0.0                 0.0              0.0                     0.0         0.000000         5.187983                            0           0           0            0              0.0         0         1         0         0          1           0            0         0          0             1       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    1.0                 0          1           6                     0                    1                         0              0                  1              0              0              0              0              0                      0               1            1                            0                     0                   0             0               0               0               0         0              0        0          83                  31          1                  0           11        240                            2                            1                              0  20260324        NaN
4  003af58f-36b8-488d-8f0d-ecfab5f1a19e1774367768698955                                             3                            0                            3                             0   0.914530                    9          3        7        3         1   4428.630                0             0.000            28        198.225            71       4084.124              0             0.0              0             0.0                 3              6.377                  0                 0.0                  0           5            0          2         80          0          1          0          12            0             0          0           0             68        0             0           0             0                      0               0                 0          0           0            0           1          71             8        80                      0                    81                          0               0                   0              81               0               0               0              81                       0                9             0                             0                      0                    0              7                0                0                0          0               0         0                   0                1                         0                           0           0          0              0         1         0              1             0             0      1        1              0.0                0.0             1.0                0.0                 0.0               0.0                 0.0              0.0                     0.0         0.000000         0.474535                            0           0           0            0             17.0         0         1         0         1          0           0            0         0          0             0       0            0          1            0                     0              0                0         0          0           0          0          0            0        0                    1.0                 0          1           0                     0                    1                         0              0                  0              1              0              0              0              1                      0               0            0                            0                     0                   0             1               0               0               0         0              0        0          23                   0          0                  0           33        123                            5                            5                              3  20260324        NaN
5  004553A4-8309-499B-A87D-E68CFDC3587F1774334530441768                                             2                            1                            1                             0  14.675214                    3          6       16        4         1   1112.706                0             0.000            28        272.630            63        501.598              0             0.0              0             0.0                 9             45.411                  0                 0.0                  0           0            0          9         79          0          0          0          62            0             1          3           0              0        0             0           1             0                      0               0                 0          0           0           75           0          63            16        79                      0                    79                          0               0                  79               0               0               0               0               0                       0                0            61                            22                      0                    0              2                2               10                0          0               0         2                   0                0                         0                           1           0          0              0         1         0              1             0             0      1        0              0.0                0.0             0.0                0.0                 0.0               0.0                 0.0              1.0                     0.0         0.000000       123.845370                            0           0           0            0              0.0         0         0         0         1          0           0            0         1          0             0       0            0          0            0                     0              0                0         0          0           0          0          0            1        0                    1.0                 0          1         124                     0                    1                         0              0                  1              0              0              0              0              0                      0               0            1                            0                     0                   0             0               0               1               0         0              0        0          37                   0          1                  0            5        132                            3                            1                              0  20260324        NaN

In [4]:
print("df records read: " + str(df.count()))
print("df columns read: " , len(df.columns))
print("df columns: ", df.columns)

df records read: 1771621511
df columns read:  169
df columns:  ['session_id', 'holiday_weekend_vacation_checkin_datekey_cnt', 'holiday_checkin_datekey_cnt', 'weekend_checkin_datekey_cnt', 'vacation_checkin_datekey_cnt', 'lead_time', 'checkin_datekey_cnt', 'goods_cnt', 'poi_cnt', 'aoi_cnt', 'city_cnt', 'stay_time', 'search_page_cnt', 'search_page_time', 'poi_list_cnt', 'poi_list_time', 'poi_info_cnt', 'poi_info_time', 'room_list_cnt', 'room_list_time', 'room_info_cnt', 'room_info_time', 'create_order_cnt', 'create_order_time', 'evaluate_page_cnt', 'evaluate_page_time', 'search_scenic_cnt', 'waitou_cnt', 'rednote_cnt', 'order_cnt', 'star2_cnt', 'star3_cnt', 'star4_cnt', 'star5_cnt', 'budget_cnt', 'express_cnt', 'business_cnt', 'theme_cnt', 'couple_cnt', 'apartment_cnt', 'inn_cnt', 'homestay_cnt', 'hostel_cnt', 'farmstay_cnt', 'family_guesthouse_cnt', 'guesthouse_cnt', 'resort_hotel_cnt', 'villa_cnt', 'family_cnt', 'esports_cnt', 'scarce_cnt', 'unique_cnt', 'lowprice_cnt', 'good_cnt', 'tourism_core_city_cnt', 'tourism_big_city_cnt', 'tourism_seasonal_city_cnt', 'tier1_city_cnt', 'new_tier1_city_cnt', 'tier2_city_cnt', 'tier3_city_cnt', 'tier4_city_cnt', 'tier5_city_cnt', 'university_cnt', 'transportation_hub_cnt', 'scenic_area_cnt', 'hospital_cnt', 'performance_sports_venue_cnt', 'convention_center_cnt', 'industrial_park_cnt', 'king_room_cnt', 'single_room_cnt', 'double_room_cnt', 'triple_room_cnt', 'suite_cnt', 'standalone_cnt', 'dorm_cnt', 'is_college_student', 'is_adult_single', 'is_adult_married_no_kids', 'is_adult_married_with_kids', 'is_over_60', 'is_senior', 'is_middle_age', 'is_young', 'is_minor', 'is_high_value', 'is_mid_value', 'is_low_value', 'is_l4', 'is_l1_3', 'is_youth_campus', 'is_business_elite', 'is_self_social', 'is_practical_life', 'is_family_guardian', 'is_vital_soldier', 'is_quality_visitor', 'is_kid_explorer', 'is_occasional_traveler', 'holiday_rnt_pct', 'travel_distance', 'is_holiday_weekend_vacation', 'is_holiday', 'is_weekend', 'is_vacation', 'order_lead_time', 'is_star2', 'is_star3', 'is_star4', 'is_star5', 'is_budget', 'is_express', 'is_business', 'is_theme', 'is_couple', 'is_apartment', 'is_inn', 'is_homestay', 'is_hostel', 'is_farmstay', 'is_family_guesthouse', 'is_guesthouse', 'is_resort_hotel', 'is_villa', 'is_family', 'is_esports', 'is_scarce', 'is_unique', 'is_lowprice', 'is_good', 'order_travel_distance', 'is_search_scenic', 'is_waitou', 'is_rednote', 'is_tourism_core_city', 'is_tourism_big_city', 'is_tourism_seasonal_city', 'is_tier1_city', 'is_new_tier1_city', 'is_tier2_city', 'is_tier3_city', 'is_tier4_city', 'is_tier5_city', 'is_university', 'is_transportation_hub', 'is_scenic_area', 'is_hospital', 'is_performance_sports_venue', 'is_convention_center', 'is_industrial_park', 'is_king_room', 'is_single_room', 'is_double_room', 'is_triple_room', 'is_suite', 'is_standalone', 'is_dorm', 'search_cnt', 'travel_session_cnt', 'is_search', 'is_travel_session', 'session_cnt', 'event_cnt', 'advance_checkin_datekey_cnt', 'sameday_checkin_datekey_cnt', 'overnight_checkin_datekey_cnt', 'dt', 'intention']

In [3]:
def metrics(df):
    # time
    df = df.withColumn('workday_cnt',col('checkin_datekey_cnt')-col('holiday_weekend_vacation_checkin_datekey_cnt'))
    df = df.withColumn('is_workday',1-col('is_holiday_weekend_vacation'))
    df = df.withColumn("is_advance_booking",when(col("order_lead_time") > 0, 1).otherwise(0))
    df = df.withColumn("is_sameday_booking",when(col("order_lead_time") == 0, 1).otherwise(0))
    df = df.withColumn("is_overnight_booking",when(col("order_lead_time") < 0, 1).otherwise(0))
    df = df.withColumn("is_holiday_weekend_vacation_advance_booking",when((col('holiday_weekend_vacation_checkin_datekey_cnt')>0)&(col('advance_checkin_datekey_cnt')>0),1).otherwise(0))
    df = df.withColumn("is_holiday_weekend_vacation_sameday_booking",when((col('holiday_weekend_vacation_checkin_datekey_cnt')>0)&(col('sameday_checkin_datekey_cnt')>0),1).otherwise(0))
    df = df.withColumn("is_holiday_weekend_vacation_overnight_booking",when((col('holiday_weekend_vacation_checkin_datekey_cnt')>0)&(col('overnight_checkin_datekey_cnt')>0),1).otherwise(0))
    df = df.withColumn("is_workday_advance_booking",when((col('workday_cnt')>0)&(col('advance_checkin_datekey_cnt')>0),1).otherwise(0))
    df = df.withColumn("is_workday_sameday_booking",when((col('workday_cnt')>0)&(col('sameday_checkin_datekey_cnt')>0),1).otherwise(0))
    df = df.withColumn("is_workday_overnight_booking",when((col('workday_cnt')>0)&(col('overnight_checkin_datekey_cnt')>0),1).otherwise(0))
    df = df.withColumn("is_order_holiday_weekend_vacation_advance_booking",when((col('is_holiday_weekend_vacation')==1)&(col('is_advance_booking')==1),1).otherwise(0))
    df = df.withColumn("is_order_holiday_weekend_vacation_sameday_booking",when((col('is_holiday_weekend_vacation')==1)&(col('is_sameday_booking')==1),1).otherwise(0))
    df = df.withColumn("is_order_holiday_weekend_vacation_overnight_booking",when((col('is_holiday_weekend_vacation')==1)&(col('is_overnight_booking')==1),1).otherwise(0))
    df = df.withColumn("is_order_workday_advance_booking",when((col('is_workday')==1)&(col('is_advance_booking')==1),1).otherwise(0))
    df = df.withColumn("is_order_workday_sameday_booking",when((col('is_workday')==1)&(col('is_sameday_booking')==1),1).otherwise(0))
    df = df.withColumn("is_order_workday_overnight_booking",when((col('is_workday')==1)&(col('is_overnight_booking')==1),1).otherwise(0))
    
    # distance
    df = df.withColumn("is_long_distance",when(col('travel_distance')>1000,1).otherwise(0))
    df = df.withColumn("is_mid_distance",when((col('travel_distance')>301)&(col('travel_distance')<=1000),1).otherwise(0))
    df = df.withColumn("is_nearby_distance",when((col('travel_distance')>51)&(col('travel_distance')<=300),1).otherwise(0))
    df = df.withColumn("is_short_distance",when(col('travel_distance')<=50,1).otherwise(0))
    df = df.withColumn("is_order_long_distance",when(col('order_travel_distance')>1000,1).otherwise(0))
    df = df.withColumn("is_order_mid_distance",when((col('order_travel_distance')>301)&(col('order_travel_distance')<=1000),1).otherwise(0))
    df = df.withColumn("is_order_nearby_distance",when((col('order_travel_distance')>51)&(col('order_travel_distance')<=300),1).otherwise(0))
    df = df.withColumn("is_order_short_distance",when(col('order_travel_distance')<=50,1).otherwise(0))
    
    # city
    df = df.withColumn('high_tier_city_cnt',col('tier1_city_cnt') +col('new_tier1_city_cnt') +col('tier2_city_cnt'))
    df = df.withColumn('low_tier_city_cnt',col('tier3_city_cnt') +col('tier4_city_cnt') +col('tier5_city_cnt'))
    df = df.withColumn('high_tier_city_ratio',when(col('city_cnt') > 0,col('high_tier_city_cnt') / col('city_cnt')).otherwise(0))
    df = df.withColumn('low_tier_city_ratio',when(col('city_cnt') > 0,col('low_tier_city_cnt') / col('city_cnt')).otherwise(0))
    df = df.withColumn('is_high_tier_city',when((col('is_tier1_city')==1)|(col('is_new_tier1_city')==1)|(col('is_tier2_city')==1),1).otherwise(0))
    df = df.withColumn('is_low_tier_city',when((col('is_tier3_city')==1)|(col('is_tier4_city')==1)|(col('is_tier5_city')==1),1).otherwise(0))
    df = df.withColumn('tourism_core_city_ratio',when(col('city_cnt') > 0,col('tourism_core_city_cnt') / col('city_cnt')).otherwise(0))
    df = df.withColumn('tourism_big_city_ratio',when(col('city_cnt') > 0,col('tourism_big_city_cnt') / col('city_cnt')).otherwise(0))
    df = df.withColumn('tourism_seasonal_city_ratio',when(col('city_cnt') > 0,col('tourism_seasonal_city_cnt') / col('city_cnt')).otherwise(0))
    
    # aoi
    df = df.withColumn('university_ratio', when(col('aoi_cnt')>0, col('university_cnt') / col('aoi_cnt')).otherwise(0))
    df = df.withColumn('transportation_hub_ratio', when(col('aoi_cnt')>0, col('transportation_hub_cnt') / col('aoi_cnt')).otherwise(0))
    df = df.withColumn('scenic_area_ratio', when(col('aoi_cnt')>0, col('scenic_area_cnt') / col('aoi_cnt')).otherwise(0))
    df = df.withColumn('hospital_ratio', when(col('aoi_cnt')>0, col('hospital_cnt') / col('aoi_cnt')).otherwise(0))
    df = df.withColumn('performance_sports_venue_ratio', when(col('aoi_cnt')>0, col('performance_sports_venue_cnt') / col('aoi_cnt')).otherwise(0))
    df = df.withColumn('convention_center_ratio', when(col('aoi_cnt')>0, col('convention_center_cnt') / col('aoi_cnt')).otherwise(0))
    df = df.withColumn('industrial_park_ratio', when(col('aoi_cnt')>0, col('industrial_park_cnt') / col('aoi_cnt')).otherwise(0))
    
    # poi
    df = df.withColumn('high_star_cnt',col('star3_cnt') +col('star4_cnt') +col('star5_cnt'))
    df = df.withColumn('is_high_star',when((col('is_star3')==1)|(col('is_star4')==1)|(col('is_star5')==1),1).otherwise(0))
    df = df.withColumn('high_star_ratio',when(col('poi_cnt') > 0,col('high_star_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('low_star_ratio',when(col('poi_cnt') > 0,col('star3_cnt') / col('poi_cnt')).otherwise(0))
    
    df = df.withColumn('budget_ratio', when(col('poi_cnt')>0, col('budget_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('express_ratio', when(col('poi_cnt')>0, col('express_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('business_ratio', when(col('poi_cnt')>0, col('business_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('theme_ratio', when(col('poi_cnt')>0, col('theme_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('couple_ratio', when(col('poi_cnt')>0, col('couple_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('apartment_ratio', when(col('poi_cnt')>0, col('apartment_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('inn_ratio', when(col('poi_cnt')>0, col('inn_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('homestay_ratio', when(col('poi_cnt')>0, col('homestay_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('hostel_ratio', when(col('poi_cnt')>0, col('hostel_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('farmstay_ratio', when(col('poi_cnt')>0, col('farmstay_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('family_guesthouse_ratio', when(col('poi_cnt')>0, col('family_guesthouse_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('guesthouse_ratio', when(col('poi_cnt')>0, col('guesthouse_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('resort_hotel_ratio', when(col('poi_cnt')>0, col('resort_hotel_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('villa_ratio', when(col('poi_cnt')>0, col('villa_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('family_ratio', when(col('poi_cnt')>0, col('family_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('esports_ratio', when(col('poi_cnt')>0, col('esports_cnt') / col('poi_cnt')).otherwise(0))
    
    df = df.withColumn('scarce_ratio', when(col('poi_cnt')>0, col('scarce_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('unique_ratio', when(col('poi_cnt')>0, col('unique_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('lowprice_ratio', when(col('poi_cnt')>0, col('lowprice_cnt') / col('poi_cnt')).otherwise(0))
    df = df.withColumn('good_ratio', when(col('poi_cnt')>0, col('good_cnt') / col('poi_cnt')).otherwise(0))
    
    # goods
    df = df.withColumn('king_room_ratio', when(col('goods_cnt')>0, col('king_room_cnt') / col('goods_cnt')).otherwise(0))
    df = df.withColumn('single_room_ratio', when(col('goods_cnt')>0, col('single_room_cnt') / col('goods_cnt')).otherwise(0))
    df = df.withColumn('double_room_ratio', when(col('goods_cnt')>0, col('double_room_cnt') / col('goods_cnt')).otherwise(0))
    df = df.withColumn('triple_room_ratio', when(col('goods_cnt')>0, col('triple_room_cnt') / col('goods_cnt')).otherwise(0))
    df = df.withColumn('suite_ratio', when(col('goods_cnt')>0, col('suite_cnt') / col('goods_cnt')).otherwise(0))
    df = df.withColumn('standalone_ratio', when(col('goods_cnt')>0, col('standalone_cnt') / col('goods_cnt')).otherwise(0))
    df = df.withColumn('dorm_ratio', when(col('goods_cnt')>0, col('dorm_cnt') / col('goods_cnt')).otherwise(0))
    
    # browsing
    df = df.withColumn('avg_checkin_datekey_cnt',when(col('session_cnt')>0,col('checkin_datekey_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_city_cnt',when(col('session_cnt')>0,col('city_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_aoi_cnt',when(col('session_cnt')>0,col('aoi_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_poi_cnt',when(col('session_cnt')>0,col('poi_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_goods_cnt',when(col('session_cnt')>0,col('goods_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_stay_time',when(col('session_cnt')>0,col('stay_time')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_order_cnt',when(col('session_cnt')>0,col('order_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_search_cnt',when(col('session_cnt')>0,col('search_cnt')/col('session_cnt')).otherwise(0))
    df = df.withColumn('avg_travel_session_cnt',when(col('session_cnt')>0,col('travel_session_cnt')/col('session_cnt')).otherwise(0))
    
    df = df.withColumn('search_page_time_ratio',when(col('stay_time')>0,col('search_page_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('poi_list_time_ratio',when(col('stay_time')>0,col('poi_list_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('poi_info_time_ratio',when(col('stay_time')>0,col('poi_info_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('room_list_time_ratio',when(col('stay_time')>0,col('room_list_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('room_info_time_ratio',when(col('stay_time')>0,col('room_info_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('create_order_time_ratio',when(col('stay_time')>0,col('create_order_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('evaluate_page_time_ratio',when(col('stay_time')>0,col('evaluate_page_time')/col('stay_time')).otherwise(0))
    df = df.withColumn('search_page_cnt_ratio',when(col('event_cnt')>0,col('search_page_cnt')/col('event_cnt')).otherwise(0))
    df = df.withColumn('poi_list_cnt_ratio',when(col('event_cnt')>0,col('poi_list_cnt')/col('event_cnt')).otherwise(0))
    df = df.withColumn('poi_info_cnt_ratio',when(col('event_cnt')>0,col('poi_info_cnt')/col('event_cnt')).otherwise(0))
    df = df.withColumn('room_list_cnt_ratio',when(col('event_cnt')>0,col('room_list_cnt')/col('event_cnt')).otherwise(0))
    df = df.withColumn('room_info_cnt_ratio',when(col('event_cnt')>0,col('room_info_cnt')/col('event_cnt')).otherwise(0))
    df = df.withColumn('create_order_cnt_ratio',when(col('event_cnt')>0,col('create_order_cnt')/col('event_cnt')).otherwise(0))
    df = df.withColumn('evaluate_page_cnt_ratio',when(col('event_cnt')>0,col('evaluate_page_cnt')/col('event_cnt')).otherwise(0))
    
    df = df.withColumn('search_non_scenic_cnt',col('search_cnt')-col('search_scenic_cnt'))
    df = df.withColumn('search_scenic_ratio',when(col('search_cnt')>0,col('search_scenic_cnt')/col('search_cnt')).otherwise(0))
    df = df.withColumn('search_non_scenic_ratio',when(col('search_cnt')>0,col('search_non_scenic_cnt')/col('search_cnt')).otherwise(0))
    
    return df

In [17]:
data = metrics(df)
data = data.dropna(subset=['intention'])
data = data.toPandas()

Exception in thread "serve-DataFrame" java.net.SocketTimeoutException: Accept timed out
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.apache.spark.security.SocketAuthServer$$anon$1.run(SocketAuthServer.scala:58)
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series

data records read:  1017337
data columns read:  243
data columns:  Index(['session_id', 'holiday_weekend_vacation_checkin_datekey_cnt',
       'holiday_checkin_datekey_cnt', 'weekend_checkin_datekey_cnt',
       'vacation_checkin_datekey_cnt', 'lead_time', 'checkin_datekey_cnt',
       'goods_cnt', 'poi_cnt', 'aoi_cnt',
       ...
       'search_page_ratio', 'poi_list_ratio', 'poi_info_ratio',
       'room_list_ratio', 'room_info_ratio', 'create_order_ratio',
       'evaluate_page_ratio', 'search_non_scenic_cnt', 'search_scenic_ratio',
       'search_non_scenic_ratio'],
      dtype='object', length=243)

In [16]:
# data.to_parquet("hdfs:///user/luyiwei03/stp_data.parquet", index=False)
data = pd.read_parquet("hdfs:///user/luyiwei03/stp_data_v2.parquet")

In [5]:
print("data records read: ", len(data))
print("data columns read: " , len(data.columns))
print("data columns: ", data.columns)

data records read:  181469
data columns read:  268
data columns:  Index(['session_id', 'holiday_weekend_vacation_checkin_datekey_cnt',
       'holiday_checkin_datekey_cnt', 'weekend_checkin_datekey_cnt',
       'vacation_checkin_datekey_cnt', 'lead_time', 'checkin_datekey_cnt',
       'goods_cnt', 'poi_cnt', 'aoi_cnt',
       ...
       'search_page_cnt_ratio', 'poi_list_cnt_ratio', 'poi_info_cnt_ratio',
       'room_list_cnt_ratio', 'room_info_cnt_ratio', 'create_order_cnt_ratio',
       'evaluate_page_cnt_ratio', 'search_non_scenic_cnt',
       'search_scenic_ratio', 'search_non_scenic_ratio'],
      dtype='object', length=268)

In [6]:
corr = data.corr(numeric_only=True)['intention'].sort_values(ascending=False)
print(corr)

intention                                              1.000000
is_scenic_area                                         0.327522
is_holiday_weekend_vacation_advance_booking            0.265214
is_family_guesthouse                                   0.259861
holiday_weekend_vacation_checkin_datekey_cnt           0.255713
is_travel_session                                      0.252020
is_holiday_weekend_vacation                            0.243991
weekend_checkin_datekey_cnt                            0.239166
aoi_cnt                                                0.235329
is_advance_booking                                     0.231392
is_order_holiday_weekend_vacation_advance_booking      0.229348
advance_checkin_datekey_cnt                            0.227381
poi_cnt                                                0.224518
scenic_area_cnt                                        0.223790
poi_info_cnt_ratio                                     0.220877
search_scenic_ratio                                    0.220027
is_weekend                                             0.218442
good_cnt                                               0.205634
goods_cnt                                              0.204894
event_cnt                                              0.202713
poi_info_cnt                                           0.199074
homestay_ratio                                         0.198183
stay_time                                              0.194089
scenic_area_ratio                                      0.187961
is_holiday_weekend_vacation_sameday_booking            0.187499
homestay_cnt                                           0.187252
is_star2                                               0.184949
avg_poi_cnt                                            0.183203
is_star4                                               0.182790
unique_cnt                                             0.181374
avg_stay_time                                          0.181270
avg_goods_cnt                                          0.179711
poi_info_time                                          0.178218
holiday_rnt_pct                                        0.175072
is_workday_advance_booking                             0.173555
holiday_checkin_datekey_cnt                            0.169502
star2_cnt                                              0.167890
order_lead_time                                        0.167771
is_tourism_core_city                                   0.167752
search_cnt                                             0.167531
family_cnt                                             0.167247
double_room_cnt                                        0.164095
avg_aoi_cnt                                            0.164040
avg_travel_session_cnt                                 0.161081
is_holiday                                             0.160271
avg_search_cnt                                         0.159255
poi_list_cnt                                           0.157816
low_tier_city_cnt                                      0.157677
high_star_cnt                                          0.155371
low_tier_city_ratio                                    0.148494
is_minor                                               0.147936
lowprice_cnt                                           0.147150
search_page_cnt                                        0.145753
star3_cnt                                              0.143671
search_scenic_cnt                                      0.142151
poi_list_time                                          0.140085
search_non_scenic_cnt                                  0.138985
is_occasional_traveler                                 0.136826
city_cnt                                               0.136576
create_order_time                                      0.131187
checkin_datekey_cnt                                    0.130962
is_suite                                               0.130201
travel_session_cnt                                     0.129832
rednote_cnt                                            0.129396
tourism_core_city_ratio                                0.128621
is_mid_value                                           0.127014
king_room_cnt                                          0.126038
tourism_core_city_cnt                                  0.125907
is_unique                                              0.124830
travel_distance                                        0.124161
tourism_big_city_cnt                                   0.123928
is_rednote                                             0.123755
suite_cnt                                              0.122137
is_esports                                             0.120967
family_ratio                                           0.117228
budget_cnt                                             0.116555
high_tier_city_cnt                                     0.115019
waitou_cnt                                             0.114399
session_cnt                                            0.110123
tourism_big_city_ratio                                 0.108353
is_double_room                                         0.107997
star4_cnt                                              0.107188
create_order_cnt                                       0.106342
is_low_value                                           0.103448
resort_hotel_cnt                                       0.100609
is_triple_room                                         0.098662
tier3_city_cnt                                         0.097516
high_tier_city_ratio                                   0.096555
good_ratio                                             0.095365
unique_ratio                                           0.094530
triple_room_cnt                                        0.094222
tier4_city_cnt                                         0.094122
is_youth_campus                                        0.093970
is_long_distance                                       0.093908
tourism_seasonal_city_cnt                              0.093796
order_travel_distance                                  0.091871
new_tier1_city_cnt                                     0.091175
is_farmstay                                            0.089941
business_cnt                                           0.089785
theme_cnt                                              0.087910
is_lowprice                                            0.087670
esports_cnt                                            0.086307
order_cnt                                              0.086072
resort_hotel_ratio                                     0.084201
tourism_seasonal_city_ratio                            0.082580
scarce_cnt                                             0.082314
tier5_city_cnt                                         0.082239
is_inn                                                 0.080590
suite_ratio                                            0.080426
inn_ratio                                              0.079988
apartment_cnt                                          0.078672
esports_ratio                                          0.078475
search_page_time                                       0.077985
inn_cnt                                                0.077602
is_vital_soldier                                       0.077186
tier2_city_cnt                                         0.076930
is_college_student                                     0.076384
is_adult_single                                        0.074310
is_star3                                               0.073444
is_tourism_seasonal_city                               0.071831
theme_ratio                                            0.070534
hospital_cnt                                           0.068552
star5_cnt                                              0.068024
is_young                                               0.067943
university_cnt                                         0.067494
transportation_hub_cnt                                 0.067057
is_l1_3                                                0.066397
triple_room_ratio                                      0.066202
high_star_ratio                                        0.066083
is_low_tier_city                                       0.065436
double_room_ratio                                      0.063851
is_business                                            0.062834
is_order_holiday_weekend_vacation_sameday_booking      0.059486
avg_order_cnt                                          0.059392
performance_sports_venue_cnt                           0.056433
is_self_social                                         0.051364
is_mid_distance                                        0.045078
is_order_workday_advance_booking                       0.044988
is_holiday_weekend_vacation_overnight_booking          0.044937
is_tier5_city                                          0.044925
scarce_ratio                                           0.044568
is_senior                                              0.042795
is_express                                             0.041823
poi_list_cnt_ratio                                     0.041256
is_tier4_city                                          0.038627
is_waitou                                              0.038505
is_over_60                                             0.038009
villa_cnt                                              0.035599
is_scarce                                              0.035154
is_resort_hotel                                        0.035007
is_high_star                                           0.034036
apartment_ratio                                        0.032444
is_standalone                                          0.031921
farmstay_cnt                                           0.030702
farmstay_ratio                                         0.029258
villa_ratio                                            0.028445
standalone_cnt                                         0.028370
room_info_cnt                                          0.028175
is_hostel                                              0.027832
low_star_ratio                                         0.027637
standalone_ratio                                       0.026274
is_tier3_city                                          0.023435
evaluate_page_cnt_ratio                                0.022777
express_cnt                                            0.021096
is_good                                                0.020676
lowprice_ratio                                         0.020084
room_info_time                                         0.019091
vacation_checkin_datekey_cnt                           0.018744
lead_time                                              0.017705
tier1_city_cnt                                         0.013853
is_dorm                                                0.013105
industrial_park_cnt                                    0.012312
dorm_cnt                                               0.011734
overnight_checkin_datekey_cnt                          0.011148
single_room_cnt                                        0.010956
evaluate_page_cnt                                      0.008727
convention_center_cnt                                  0.008378
room_info_cnt_ratio                                    0.007311
is_order_holiday_weekend_vacation_overnight_booking    0.006699
dorm_ratio                                             0.005195
couple_cnt                                             0.004751
is_workday_overnight_booking                           0.003361
is_budget                                              0.002720
room_info_time_ratio                                   0.002260
is_vacation                                            0.001447
is_kid_explorer                                        0.001085
guesthouse_cnt                                         0.000735
hostel_cnt                                             0.000248
hostel_ratio                                          -0.000378
is_tier2_city                                         -0.001617
is_star5                                              -0.002090
guesthouse_ratio                                      -0.002637
couple_ratio                                          -0.002943
is_family                                             -0.002984
is_new_tier1_city                                     -0.003681
family_guesthouse_cnt                                 -0.004737
search_page_time_ratio                                -0.004902
is_homestay                                           -0.005447
avg_checkin_datekey_cnt                               -0.006146
search_page_cnt_ratio                                 -0.006251
evaluate_page_time                                    -0.007426
evaluate_page_time_ratio                              -0.008802
is_tourism_big_city                                   -0.009330
performance_sports_venue_ratio                        -0.011810
is_overnight_booking                                  -0.013837
family_guesthouse_ratio                               -0.015284
is_villa                                              -0.016323
poi_info_time_ratio                                   -0.016407
poi_list_time_ratio                                   -0.016944
industrial_park_ratio                                 -0.018595
is_guesthouse                                         -0.020884
transportation_hub_ratio                              -0.023206
is_order_workday_overnight_booking                    -0.025151
business_ratio                                        -0.025220
is_practical_life                                     -0.029544
convention_center_ratio                               -0.030084
king_room_ratio                                       -0.031630
is_convention_center                                  -0.031988
is_industrial_park                                    -0.033303
hospital_ratio                                        -0.036652
is_search                                             -0.037610
is_search_scenic                                      -0.038698
university_ratio                                      -0.039110
is_short_distance                                     -0.039955
is_performance_sports_venue                           -0.040089
is_family_guardian                                    -0.041260
avg_city_cnt                                          -0.042637
workday_cnt                                           -0.043806
is_quality_visitor                                    -0.045582
is_high_tier_city                                     -0.048058
express_ratio                                         -0.051404
budget_ratio                                          -0.052942
is_adult_married_no_kids                              -0.054878
single_room_ratio                                     -0.057754
create_order_time_ratio                               -0.061165
is_l4                                                 -0.063299
is_nearby_distance                                    -0.070849
is_tier1_city                                         -0.072306
search_non_scenic_ratio                               -0.083008
is_apartment                                          -0.084143
is_couple                                             -0.084166
is_single_room                                        -0.085607
is_adult_married_with_kids                            -0.088270
is_transportation_hub                                 -0.097383
is_university                                         -0.100812
is_hospital                                           -0.101657
is_king_room                                          -0.109807
create_order_cnt_ratio                                -0.112116
sameday_checkin_datekey_cnt                           -0.118680
is_theme                                              -0.129758
is_middle_age                                         -0.170235
is_high_value                                         -0.180775
is_workday_sameday_booking                            -0.208191
is_sameday_booking                                    -0.231135
is_workday                                            -0.243991
is_order_workday_sameday_booking                      -0.289335
is_business_elite                                     -0.305889
room_list_cnt                                               NaN
room_list_time                                              NaN
is_order_long_distance                                      NaN
is_order_mid_distance                                       NaN
is_order_nearby_distance                                    NaN
is_order_short_distance                                     NaN
room_list_time_ratio                                        NaN
room_list_cnt_ratio                                         NaN
Name: intention, dtype: float64

In [17]:
X = data.drop(columns=['intention','session_id','dt','level3_biz_code'])
y = data['intention']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=3, stratify=y)

scale_pos_weight = y_train.value_counts()[0] / y_train.value_counts()[1]

train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

In [10]:
params = {
    'objective': 'binary',
    'metric': 'auc',
    'boosting_type': 'gbdt',
    'learning_rate': 0.01,
    'num_leaves': 256,
    'max_depth': 12,
    'min_data_in_leaf': 150,
    'lambda_l1': 0.1,
    'lambda_l2': 2,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.9,
    'bagging_freq': 5,
    'min_gain_to_split': 0,
    'scale_pos_weight': 1.2,
    'max_bin': 255,
    'verbose': -1,
    'seed': 0
}

lgbm = lgb.train(
    params,
    train_data,
    valid_sets=[train_data, test_data],
    valid_names=['train','valid'],
    num_boost_round=10000,
    callbacks=[early_stopping(stopping_rounds=200), log_evaluation(100)]
)

Training until validation scores don't improve for 200 rounds
[100]	train's auc: 0.903601	valid's auc: 0.890518
[200]	train's auc: 0.915306	valid's auc: 0.898573
[300]	train's auc: 0.924407	valid's auc: 0.904585
[400]	train's auc: 0.931578	valid's auc: 0.908861
[500]	train's auc: 0.936925	valid's auc: 0.911816
[600]	train's auc: 0.941532	valid's auc: 0.91383
[700]	train's auc: 0.945284	valid's auc: 0.915358
[800]	train's auc: 0.948743	valid's auc: 0.916373
[900]	train's auc: 0.951956	valid's auc: 0.917165
[1000]	train's auc: 0.95493	valid's auc: 0.917906
[1100]	train's auc: 0.95722	valid's auc: 0.918364
[1200]	train's auc: 0.959404	valid's auc: 0.918735
[1300]	train's auc: 0.961927	valid's auc: 0.919107
[1400]	train's auc: 0.963923	valid's auc: 0.919309
[1500]	train's auc: 0.965851	valid's auc: 0.919571
[1600]	train's auc: 0.967714	valid's auc: 0.919794
[1700]	train's auc: 0.969431	valid's auc: 0.919949
[1800]	train's auc: 0.971093	valid's auc: 0.920135
[1900]	train's auc: 0.972536	valid's auc: 0.92024
[2000]	train's auc: 0.973824	valid's auc: 0.920372
[2100]	train's auc: 0.97549	valid's auc: 0.920469
[2200]	train's auc: 0.976946	valid's auc: 0.920549
[2300]	train's auc: 0.978335	valid's auc: 0.920644
[2400]	train's auc: 0.979674	valid's auc: 0.920692
[2500]	train's auc: 0.980802	valid's auc: 0.920778
[2600]	train's auc: 0.982003	valid's auc: 0.920865
[2700]	train's auc: 0.982994	valid's auc: 0.920908
[2800]	train's auc: 0.984059	valid's auc: 0.920955
[2900]	train's auc: 0.984945	valid's auc: 0.920966
[3000]	train's auc: 0.985771	valid's auc: 0.92101
[3100]	train's auc: 0.986582	valid's auc: 0.92105
[3200]	train's auc: 0.987414	valid's auc: 0.921065
[3300]	train's auc: 0.988246	valid's auc: 0.921042
Early stopping, best iteration is:
[3171]	train's auc: 0.987193	valid's auc: 0.921082

In [11]:
y_pred_prob = lgbm.predict(X_test)

cal_prob_raw = lgbm.predict(X_test,num_iteration=lgbm.best_iteration)

iso = IsotonicRegression(out_of_bounds='clip')
iso.fit(cal_prob_raw,y_test)

test_prob_raw = lgbm.predict(X_test,num_iteration=lgbm.best_iteration)
test_prob_cal = iso.transform(test_prob_raw)

print("Raw AUC:", roc_auc_score(y_test, test_prob_raw))
print("Calibrated AUC:", roc_auc_score(y_test, test_prob_cal))
print("Raw LogLoss:", log_loss(y_test, test_prob_raw))
print("Calibrated LogLoss:", log_loss(y_test, test_prob_cal))

best_acc=0
best_threshold=0.5
for t in np.arange(0.1, 0.9, 0.01):
    pred = (test_prob_cal >= t).astype(int)
    acc = accuracy_score(y_test, pred)
    if acc > best_acc:
        best_acc = acc
        best_threshold = t

y_pred = (test_prob_cal >= best_threshold).astype(int)

print("Best threshold:",best_threshold)
print("Best Accuracy:",best_acc)
print("AUC:",roc_auc_score(y_test,y_pred_prob))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Raw AUC: 0.9210823368607524
Calibrated AUC: 0.9218444406386397
Raw LogLoss: 0.3573860529686011
Calibrated LogLoss: 0.3515797365291188
Best threshold: 0.4999999999999998
Best Accuracy: 0.8416267151595305
AUC: 0.9210823368607524
              precision    recall  f1-score   support

           0       0.81      0.84      0.82      7983
           1       0.87      0.84      0.86     10164

    accuracy                           0.84     18147
   macro avg       0.84      0.84      0.84     18147
weighted avg       0.84      0.84      0.84     18147

[[6714 1269]
 [1605 8559]]

In [12]:
gain = lgbm.feature_importance(importance_type='gain')
features = lgbm.feature_name()

fi = pd.DataFrame({
    'feature': features,
    'gain': gain
}).sort_values(by='gain', ascending=False)

print(fi)

                                                 feature          gain
64                                       scenic_area_cnt  1.089679e+06
91                                     is_business_elite  5.288892e+05
218                                       homestay_ratio  2.740864e+05
202                                    scenic_area_ratio  2.726106e+05
40                                          homestay_cnt  2.325320e+05
100                                      travel_distance  2.068126e+05
99                                       holiday_rnt_pct  1.783443e+05
246                               avg_travel_session_cnt  1.593129e+05
101                          is_holiday_weekend_vacation  1.388366e+05
128                                          is_lowprice  1.154931e+05
82                                         is_middle_age  1.073046e+05
133                                           is_rednote  1.069106e+05
256                                   poi_info_cnt_ratio  1.051937e+05
175                           is_workday_sameday_booking  9.998675e+04
85                                         is_high_value  9.961753e+04
84                                              is_minor  9.917459e+04
200                                     university_ratio  9.328602e+04
158                                   travel_session_cnt  7.919066e+04
225                                         family_ratio  7.835010e+04
4                                              lead_time  7.754584e+04
226                                        esports_ratio  7.542846e+04
231                                      king_room_ratio  7.374133e+04
181                     is_order_workday_sameday_booking  7.237814e+04
263                              search_non_scenic_ratio  7.200164e+04
228                                         unique_ratio  7.016472e+04
203                                       hospital_ratio  7.004815e+04
240                                          avg_aoi_cnt  6.999512e+04
22                                     create_order_time  6.956590e+04
230                                           good_ratio  6.865107e+04
249                                  poi_info_time_ratio  6.845873e+04
211                                         budget_ratio  6.762084e+04
248                                  poi_list_time_ratio  6.679396e+04
243                                        avg_stay_time  6.551653e+04
252                              create_order_time_ratio  6.231148e+04
105                                      order_lead_time  6.177057e+04
232                                    single_room_ratio  6.109271e+04
16                                         poi_info_time  5.588122e+04
223                                   resort_hotel_ratio  5.570358e+04
262                                  search_scenic_ratio  5.514640e+04
213                                       business_ratio  5.394748e+04
233                                    double_room_ratio  5.334955e+04
259                               create_order_cnt_ratio  5.183627e+04
164                          sameday_checkin_datekey_cnt  4.491905e+04
50                                            unique_cnt  4.483447e+04
201                             transportation_hub_ratio  4.417963e+04
229                                       lowprice_ratio  4.361769e+04
27                                           rednote_cnt  4.305144e+04
45                                      resort_hotel_cnt  4.286892e+04
255                                   poi_list_cnt_ratio  4.226215e+04
212                                        express_ratio  4.182225e+04
25                                     search_scenic_cnt  3.998335e+04
10                                             stay_time  3.987529e+04
244                                        avg_order_cnt  3.875440e+04
166                                          workday_cnt  3.763466e+04
52                                              good_cnt  3.663257e+04
143                                        is_university  3.533784e+04
47                                            family_cnt  3.350389e+04
254                                search_page_cnt_ratio  3.319990e+04
14                                         poi_list_time  3.196761e+04
214                                          theme_ratio  3.133295e+04
62                                        university_cnt  3.094066e+04
69                                         king_room_cnt  3.017392e+04
162                                            event_cnt  3.002327e+04
65                                          hospital_cnt  2.957370e+04
241                                          avg_poi_cnt  2.884136e+04
29                                             star2_cnt  2.866777e+04
197                              tourism_core_city_ratio  2.859713e+04
242                                        avg_goods_cnt  2.831613e+04
56                                        tier1_city_cnt  2.826994e+04
194                                  low_tier_city_ratio  2.776080e+04
28                                             order_cnt  2.766495e+04
198                               tourism_big_city_ratio  2.749539e+04
210                                       low_star_ratio  2.728710e+04
209                                      high_star_ratio  2.727832e+04
245                                       avg_search_cnt  2.712772e+04
33                                            budget_cnt  2.668128e+04
150                                         is_king_room  2.645826e+04
247                               search_page_time_ratio  2.622960e+04
71                                       double_room_cnt  2.565695e+04
0           holiday_weekend_vacation_checkin_datekey_cnt  2.550780e+04
120                                 is_family_guesthouse  2.499456e+04
146                                          is_hospital  2.408196e+04
204                       performance_sports_venue_ratio  2.385444e+04
97                                       is_kid_explorer  2.379562e+04
63                                transportation_hub_cnt  2.369473e+04
76                                    is_college_student  2.357028e+04
51                                          lowprice_cnt  2.326680e+04
8                                                aoi_cnt  2.259715e+04
193                                 high_tier_city_ratio  2.236936e+04
137                                        is_tier1_city  2.227415e+04
35                                          business_cnt  2.170031e+04
192                                    low_tier_city_cnt  2.135975e+04
216                                      apartment_ratio  2.133952e+04
199                          tourism_seasonal_city_ratio  2.100115e+04
54                                  tourism_big_city_cnt  2.068914e+04
12                                      search_page_time  2.045100e+04
21                                      create_order_cnt  2.044474e+04
48                                           esports_cnt  2.023567e+04
238                              avg_checkin_datekey_cnt  1.983363e+04
15                                          poi_info_cnt  1.983118e+04
235                                          suite_ratio  1.979332e+04
73                                             suite_cnt  1.972133e+04
145                                       is_scenic_area  1.956705e+04
58                                        tier2_city_cnt  1.951821e+04
83                                              is_young  1.945747e+04
234                                    triple_room_ratio  1.879288e+04
98                                is_occasional_traveler  1.839236e+04
53                                 tourism_core_city_cnt  1.827965e+04
154                                             is_suite  1.714244e+04
191                                   high_tier_city_cnt  1.697981e+04
57                                    new_tier1_city_cnt  1.672083e+04
92                                        is_self_social  1.604755e+04
185                                   is_nearby_distance  1.600331e+04
113                                             is_theme  1.577493e+04
217                                            inn_ratio  1.565496e+04
79                            is_adult_married_with_kids  1.557860e+04
261                                search_non_scenic_cnt  1.556169e+04
207                                        high_star_cnt  1.547065e+04
96                                    is_quality_visitor  1.521431e+04
13                                          poi_list_cnt  1.500101e+04
115                                         is_apartment  1.498149e+04
167                                           is_workday  1.486899e+04
239                                         avg_city_cnt  1.478556e+04
70                                       single_room_cnt  1.472322e+04
1                            holiday_checkin_datekey_cnt  1.455763e+04
77                                       is_adult_single  1.452474e+04
227                                         scarce_ratio  1.410030e+04
66                          performance_sports_venue_cnt  1.403701e+04
157                                           search_cnt  1.403017e+04
30                                             star3_cnt  1.347220e+04
60                                        tier4_city_cnt  1.263481e+04
144                                is_transportation_hub  1.262056e+04
59                                        tier3_city_cnt  1.245400e+04
72                                       triple_room_cnt  1.219566e+04
102                                           is_holiday  1.210613e+04
171          is_holiday_weekend_vacation_advance_booking  1.181814e+04
31                                             star4_cnt  1.173099e+04
7                                                poi_cnt  1.137206e+04
134                                 is_tourism_core_city  1.129046e+04
6                                              goods_cnt  1.106767e+04
90                                       is_youth_campus  1.102007e+04
36                                             theme_cnt  1.097344e+04
55                             tourism_seasonal_city_cnt  1.088567e+04
34                                           express_cnt  1.022010e+04
86                                          is_mid_value  1.017218e+04
61                                        tier5_city_cnt  1.011252e+04
26                                            waitou_cnt  9.740027e+03
81                                             is_senior  9.711411e+03
206                                industrial_park_ratio  8.418352e+03
151                                       is_single_room  8.180915e+03
205                              convention_center_ratio  7.910831e+03
88                                                 is_l4  7.885890e+03
163                          advance_checkin_datekey_cnt  7.662157e+03
49                                            scarce_cnt  7.346874e+03
38                                         apartment_cnt  7.319096e+03
161                                          session_cnt  7.263294e+03
196                                     is_low_tier_city  7.220818e+03
5                                    checkin_datekey_cnt  7.091436e+03
87                                          is_low_value  7.022923e+03
89                                               is_l1_3  6.415069e+03
237                                           dorm_ratio  6.202468e+03
219                                         hostel_ratio  5.962026e+03
159                                            is_search  5.959256e+03
2                            weekend_checkin_datekey_cnt  5.908956e+03
11                                       search_page_cnt  5.795784e+03
131                                     is_search_scenic  5.658735e+03
68                                   industrial_park_cnt  5.575499e+03
195                                    is_high_tier_city  5.456110e+03
152                                       is_double_room  5.277997e+03
140                                        is_tier3_city  5.033599e+03
114                                            is_couple  4.952786e+03
78                              is_adult_married_no_kids  4.908688e+03
221                              family_guesthouse_ratio  4.888749e+03
135                                  is_tourism_big_city  4.801606e+03
95                                      is_vital_soldier  4.426487e+03
153                                       is_triple_room  4.283283e+03
186                                    is_short_distance  4.144577e+03
108                                             is_star4  4.142498e+03
172          is_holiday_weekend_vacation_sameday_booking  4.095501e+03
41                                            hostel_cnt  4.084866e+03
177    is_order_holiday_weekend_vacation_advance_booking  4.052260e+03
103                                           is_weekend  4.028095e+03
180                     is_order_workday_advance_booking  3.794598e+03
94                                    is_family_guardian  3.684811e+03
139                                        is_tier2_city  3.622187e+03
136                             is_tourism_seasonal_city  3.551721e+03
42                                          farmstay_cnt  3.454022e+03
132                                            is_waitou  3.453046e+03
165                        overnight_checkin_datekey_cnt  3.348768e+03
80                                            is_over_60  3.278305e+03
130                                order_travel_distance  3.072992e+03
178    is_order_holiday_weekend_vacation_sameday_booking  3.036367e+03
109                                             is_star5  2.925734e+03
32                                             star5_cnt  2.832487e+03
75                                              dorm_cnt  2.709999e+03
9                                               city_cnt  2.705959e+03
224                                          villa_ratio  2.620897e+03
67                                 convention_center_cnt  2.567007e+03
141                                        is_tier4_city  2.436126e+03
220                                       farmstay_ratio  2.411786e+03
127                                            is_unique  2.368170e+03
93                                     is_practical_life  2.291583e+03
208                                         is_high_star  2.247637e+03
260                              evaluate_page_cnt_ratio  2.238879e+03
174                           is_workday_advance_booking  2.131344e+03
138                                    is_new_tier1_city  2.014298e+03
184                                      is_mid_distance  2.004416e+03
39                                               inn_cnt  1.983515e+03
169                                   is_sameday_booking  1.892041e+03
160                                    is_travel_session  1.730880e+03
147                          is_performance_sports_venue  1.707219e+03
43                                 family_guesthouse_cnt  1.413045e+03
176                         is_workday_overnight_booking  1.342481e+03
23                                     evaluate_page_cnt  1.297098e+03
142                                        is_tier5_city  1.271001e+03
110                                            is_budget  1.264421e+03
258                                  room_info_cnt_ratio  1.101543e+03
173        is_holiday_weekend_vacation_overnight_booking  1.019733e+03
251                                 room_info_time_ratio  9.920122e+02
148                                 is_convention_center  9.775655e+02
107                                             is_star3  9.613066e+02
236                                     standalone_ratio  9.304796e+02
118                                            is_hostel  7.487212e+02
129                                              is_good  6.746471e+02
149                                   is_industrial_park  6.572715e+02
222                                     guesthouse_ratio  6.441309e+02
168                                   is_advance_booking  6.015094e+02
116                                               is_inn  5.985512e+02
215                                         couple_ratio  5.934632e+02
111                                           is_express  5.545632e+02
24                                    evaluate_page_time  5.009285e+02
20                                        room_info_time  4.923488e+02
183                                     is_long_distance  4.142632e+02
119                                          is_farmstay  4.077936e+02
155                                        is_standalone  4.051249e+02
106                                             is_star2  3.894117e+02
74                                        standalone_cnt  3.662840e+02
121                                        is_guesthouse  3.284715e+02
156                                              is_dorm  2.803385e+02
46                                             villa_cnt  2.410234e+02
182                   is_order_workday_overnight_booking  2.270744e+02
179  is_order_holiday_weekend_vacation_overnight_booking  2.166904e+02
253                             evaluate_page_time_ratio  1.978912e+02
170                                 is_overnight_booking  1.941048e+02
125                                           is_esports  1.552176e+02
112                                          is_business  1.352533e+02
19                                         room_info_cnt  1.104146e+02
44                                        guesthouse_cnt  9.813285e+01
37                                            couple_cnt  3.707066e+01
126                                            is_scarce  2.069720e+01
3                           vacation_checkin_datekey_cnt  2.956660e+00
190                              is_order_short_distance  0.000000e+00
257                                  room_list_cnt_ratio  0.000000e+00
104                                          is_vacation  0.000000e+00
123                                             is_villa  0.000000e+00
250                                 room_list_time_ratio  0.000000e+00
187                               is_order_long_distance  0.000000e+00
124                                            is_family  0.000000e+00
17                                         room_list_cnt  0.000000e+00
18                                        room_list_time  0.000000e+00
189                             is_order_nearby_distance  0.000000e+00
117                                          is_homestay  0.000000e+00
122                                      is_resort_hotel  0.000000e+00
188                                is_order_mid_distance  0.000000e+00

In [13]:
lgbm.save_model('lgb_intention_model_v2.txt')
joblib.dump(iso,'lgb_intention_model_v2_iso.pkl')
with open('lgb_intention_model_v2.txt.meta', 'w') as f:
    json.dump({'best_threshold': best_threshold}, f)

In [27]:
dtrain = xgb.DMatrix(X_train,label=y_train)
dval = xgb.DMatrix(X_test,label=y_test)

In [29]:
params = {
    'objective':'binary:logistic',
    'eval_metric':'auc',
    'booster':'gbtree',
    'learning_rate':0.02,
    'max_depth':10,
    'min_child_weight':50,
    'reg_alpha':1,
    'reg_lambda':5,
    'colsample_bytree':0.7,
    'subsample':0.9,
    'gamma':0.1,
    'scale_pos_weight':0.8,
    'tree_method':'hist',
    'max_bin':255,
    'seed':0,
    'n_jobs':-1
}

xgbm = xgb.train(
    params,
    dtrain,
    num_boost_round=10000,
    evals=[(dtrain,'train'),(dval,'valid')],
    early_stopping_rounds=200,
    verbose_eval=100
)

[0]	train-auc:0.85330	valid-auc:0.84387
[100]	train-auc:0.90753	valid-auc:0.89419
[200]	train-auc:0.92023	valid-auc:0.90467
[300]	train-auc:0.92742	valid-auc:0.91001
[400]	train-auc:0.93208	valid-auc:0.91285
[500]	train-auc:0.93585	valid-auc:0.91475
[600]	train-auc:0.93892	valid-auc:0.91589
[700]	train-auc:0.94149	valid-auc:0.91667
[800]	train-auc:0.94381	valid-auc:0.91720
[900]	train-auc:0.94594	valid-auc:0.91764
[1000]	train-auc:0.94796	valid-auc:0.91795
[1100]	train-auc:0.94975	valid-auc:0.91827
[1200]	train-auc:0.95146	valid-auc:0.91847
[1300]	train-auc:0.95311	valid-auc:0.91872
[1400]	train-auc:0.95462	valid-auc:0.91885
[1500]	train-auc:0.95607	valid-auc:0.91898
[1600]	train-auc:0.95749	valid-auc:0.91908
[1700]	train-auc:0.95889	valid-auc:0.91916
[1800]	train-auc:0.96025	valid-auc:0.91922
[1900]	train-auc:0.96140	valid-auc:0.91926
[2000]	train-auc:0.96257	valid-auc:0.91931
[2100]	train-auc:0.96372	valid-auc:0.91941
[2200]	train-auc:0.96470	valid-auc:0.91945
[2300]	train-auc:0.96579	valid-auc:0.91948
[2400]	train-auc:0.96680	valid-auc:0.91953
[2500]	train-auc:0.96776	valid-auc:0.91957
[2600]	train-auc:0.96871	valid-auc:0.91959
[2700]	train-auc:0.96973	valid-auc:0.91963
[2800]	train-auc:0.97055	valid-auc:0.91965
[2900]	train-auc:0.97138	valid-auc:0.91962
[3000]	train-auc:0.97222	valid-auc:0.91964
[3100]	train-auc:0.97309	valid-auc:0.91963
[3152]	train-auc:0.97352	valid-auc:0.91964

In [30]:
cal_prob_raw = xgbm.predict(dval,iteration_range=(0,xgbm.best_iteration+1))

iso = IsotonicRegression(out_of_bounds='clip')
iso.fit(cal_prob_raw,y_test)

test_prob_raw = xgbm.predict(dval,iteration_range=(0,xgbm.best_iteration+1))
test_prob_cal = iso.transform(test_prob_raw)

print("Raw AUC:", roc_auc_score(y_test, test_prob_raw))
print("Calibrated AUC:", roc_auc_score(y_test, test_prob_cal))
print("Raw LogLoss:", log_loss(y_test, test_prob_raw))
print("Calibrated LogLoss:", log_loss(y_test, test_prob_cal))

best_acc=0
best_threshold=0.5
for t in np.arange(0.1, 0.9, 0.01):
    pred = (test_prob_cal >= t).astype(int)
    acc = accuracy_score(y_test, pred)
    if acc > best_acc:
        best_acc = acc
        best_threshold = t

y_pred = (test_prob_cal >= best_threshold).astype(int)

print("Best threshold:",best_threshold)
print("Best Accuracy:",best_acc)
print("AUC:",roc_auc_score(y_test,y_pred_prob))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Raw AUC: 0.9196558255951512
Calibrated AUC: 0.9204857141082415
Raw LogLoss: 0.3596105441149252
Calibrated LogLoss: 0.35435714312451794
Best threshold: 0.48999999999999977
Best Accuracy: 0.8416818206866149
AUC: 0.9201769792883865
              precision    recall  f1-score   support

           0       0.81      0.84      0.82      7983
           1       0.87      0.84      0.86     10164

    accuracy                           0.84     18147
   macro avg       0.84      0.84      0.84     18147
weighted avg       0.84      0.84      0.84     18147

[[6686 1297]
 [1576 8588]]

In [31]:
gain = xgbm.get_score(importance_type='gain')
features = X_train.columns

fi = pd.DataFrame({
    'feature': features,
    'gain': [gain.get(f,0) for f in features]
}).sort_values(by='gain', ascending=False)

print(fi)

                                                 feature        gain
91                                     is_business_elite  352.958954
40                                          homestay_cnt  161.451904
64                                       scenic_area_cnt  152.809616
167                                           is_workday  110.756592
246                               avg_travel_session_cnt  107.028740
120                                 is_family_guesthouse  103.704536
181                     is_order_workday_sameday_booking  101.168335
84                                              is_minor  100.408813
128                                          is_lowprice   96.025513
175                           is_workday_sameday_booking   93.554993
158                                   travel_session_cnt   91.806244
145                                       is_scenic_area   74.048965
25                                     search_scenic_cnt   69.024277
218                                       homestay_ratio   67.964050
101                          is_holiday_weekend_vacation   66.744400
262                                  search_scenic_ratio   65.792152
45                                      resort_hotel_cnt   64.008705
160                                    is_travel_session   57.575600
82                                         is_middle_age   56.692654
263                              search_non_scenic_ratio   50.875042
137                                        is_tier1_city   49.685341
223                                   resort_hotel_ratio   46.360962
202                                    scenic_area_ratio   37.594711
27                                           rednote_cnt   35.213177
76                                    is_college_student   34.321129
96                                    is_quality_visitor   32.765564
108                                             is_star4   32.369949
235                                          suite_ratio   31.692963
148                                 is_convention_center   29.527178
143                                        is_university   29.348623
217                                            inn_ratio   28.021858
85                                         is_high_value   27.944967
42                                          farmstay_cnt   27.619062
0           holiday_weekend_vacation_checkin_datekey_cnt   24.970215
234                                    triple_room_ratio   24.690950
232                                    single_room_ratio   23.107574
114                                            is_couple   22.751928
73                                             suite_cnt   22.608591
146                                          is_hospital   21.837543
221                              family_guesthouse_ratio   21.434454
115                                         is_apartment   21.267868
144                                is_transportation_hub   21.094641
226                                        esports_ratio   21.017986
164                          sameday_checkin_datekey_cnt   20.733191
134                                 is_tourism_core_city   20.152779
92                                        is_self_social   19.947577
196                                     is_low_tier_city   19.631241
151                                       is_single_room   19.273832
197                              tourism_core_city_ratio   19.171795
78                              is_adult_married_no_kids   18.692612
97                                       is_kid_explorer   18.416300
185                                   is_nearby_distance   18.240507
150                                         is_king_room   17.255070
113                                             is_theme   17.117708
99                                       holiday_rnt_pct   16.940676
220                                       farmstay_ratio   16.687822
81                                             is_senior   16.622200
186                                    is_short_distance   16.571264
119                                          is_farmstay   16.502596
199                          tourism_seasonal_city_ratio   14.937706
140                                        is_tier3_city   14.893298
166                                          workday_cnt   14.687062
195                                    is_high_tier_city   14.589357
171          is_holiday_weekend_vacation_advance_booking   14.169182
102                                           is_holiday   13.943467
136                             is_tourism_seasonal_city   13.822724
43                                 family_guesthouse_cnt   13.613467
70                                       single_room_cnt   13.462610
214                                          theme_ratio   13.446868
98                                is_occasional_traveler   13.424834
1                            holiday_checkin_datekey_cnt   13.257178
23                                     evaluate_page_cnt   12.946298
116                                               is_inn   12.869655
48                                           esports_cnt   12.769195
72                                       triple_room_cnt   12.642632
53                                 tourism_core_city_cnt   12.552136
80                                            is_over_60   12.331059
225                                         family_ratio   12.108420
212                                        express_ratio   12.071548
240                                          avg_aoi_cnt   12.062428
90                                       is_youth_campus   11.667595
183                                     is_long_distance   11.142344
83                                              is_young   11.109957
56                                        tier1_city_cnt   10.813491
41                                            hostel_cnt   10.752949
177    is_order_holiday_weekend_vacation_advance_booking   10.663601
200                                     university_ratio   10.579286
139                                        is_tier2_city   10.148628
55                             tourism_seasonal_city_cnt   10.143071
205                              convention_center_ratio    9.473474
180                     is_order_workday_advance_booking    9.427961
93                                     is_practical_life    9.090680
47                                            family_cnt    9.044696
79                            is_adult_married_with_kids    9.009602
100                                      travel_distance    8.983497
87                                          is_low_value    8.954549
135                                  is_tourism_big_city    8.911422
141                                        is_tier4_city    8.900251
86                                          is_mid_value    8.859745
125                                           is_esports    8.605468
133                                           is_rednote    8.476094
112                                          is_business    8.451205
203                                       hospital_ratio    8.416251
4                                              lead_time    8.409240
131                                     is_search_scenic    8.402414
105                                      order_lead_time    8.371144
8                                                aoi_cnt    8.325525
165                        overnight_checkin_datekey_cnt    8.140914
224                                          villa_ratio    8.099575
34                                           express_cnt    8.098526
219                                         hostel_ratio    8.043230
256                                   poi_info_cnt_ratio    7.938858
194                                  low_tier_city_ratio    7.718207
129                                              is_good    7.687716
77                                       is_adult_single    7.652905
142                                        is_tier5_city    7.620131
149                                   is_industrial_park    7.559972
228                                         unique_ratio    7.504878
50                                            unique_cnt    7.445278
178    is_order_holiday_weekend_vacation_sameday_booking    7.382845
36                                             theme_cnt    7.290987
118                                            is_hostel    7.184438
109                                             is_star5    7.140303
248                                  poi_list_time_ratio    6.964895
127                                            is_unique    6.886075
192                                    low_tier_city_cnt    6.867759
132                                            is_waitou    6.816445
154                                             is_suite    6.738966
147                          is_performance_sports_venue    6.710421
213                                       business_ratio    6.699908
58                                        tier2_city_cnt    6.631687
173        is_holiday_weekend_vacation_overnight_booking    6.543538
233                                    double_room_ratio    6.533560
201                             transportation_hub_ratio    6.457688
39                                               inn_cnt    6.444222
230                                           good_ratio    6.382868
211                                         budget_ratio    6.375943
159                                            is_search    6.284092
206                                industrial_park_ratio    6.117201
231                                      king_room_ratio    6.062222
163                          advance_checkin_datekey_cnt    6.031349
174                           is_workday_advance_booking    6.016492
130                                order_travel_distance    5.978573
216                                      apartment_ratio    5.973571
49                                            scarce_cnt    5.896323
121                                        is_guesthouse    5.853530
168                                   is_advance_booking    5.824015
138                                    is_new_tier1_city    5.817186
59                                        tier3_city_cnt    5.806813
60                                        tier4_city_cnt    5.755356
176                         is_workday_overnight_booking    5.709805
204                       performance_sports_venue_ratio    5.671563
61                                        tier5_city_cnt    5.664073
35                                          business_cnt    5.657434
198                               tourism_big_city_ratio    5.544920
71                                       double_room_cnt    5.541494
208                                         is_high_star    5.528874
260                              evaluate_page_cnt_ratio    5.496102
9                                               city_cnt    5.424804
24                                    evaluate_page_time    5.375867
152                                       is_double_room    5.375386
227                                         scarce_ratio    5.330593
94                                    is_family_guardian    5.254349
52                                              good_cnt    5.253935
68                                   industrial_park_cnt    5.226296
157                                           search_cnt    5.221528
13                                          poi_list_cnt    5.202905
156                                              is_dorm    5.146530
88                                                 is_l4    5.122039
247                               search_page_time_ratio    5.111490
95                                      is_vital_soldier    5.107349
28                                             order_cnt    5.104045
69                                         king_room_cnt    5.102371
261                                search_non_scenic_cnt    5.096610
14                                         poi_list_time    5.057462
169                                   is_sameday_booking    4.987318
89                                               is_l1_3    4.983649
65                                          hospital_cnt    4.976430
63                                transportation_hub_cnt    4.974758
31                                             star4_cnt    4.964356
16                                         poi_info_time    4.945332
209                                      high_star_ratio    4.929539
243                                        avg_stay_time    4.928490
66                          performance_sports_venue_cnt    4.927620
237                                           dorm_ratio    4.926514
245                                       avg_search_cnt    4.922872
38                                         apartment_cnt    4.922208
193                                 high_tier_city_ratio    4.871530
62                                        university_cnt    4.871152
2                            weekend_checkin_datekey_cnt    4.869902
191                                   high_tier_city_cnt    4.862016
57                                    new_tier1_city_cnt    4.854649
5                                    checkin_datekey_cnt    4.828445
162                                            event_cnt    4.828025
67                                 convention_center_cnt    4.826021
252                              create_order_time_ratio    4.778511
33                                            budget_cnt    4.777615
107                                             is_star3    4.768036
253                             evaluate_page_time_ratio    4.759168
22                                     create_order_time    4.757589
229                                       lowprice_ratio    4.754001
207                                        high_star_cnt    4.708049
46                                             villa_cnt    4.707078
106                                             is_star2    4.692585
103                                           is_weekend    4.689777
54                                  tourism_big_city_cnt    4.689717
12                                      search_page_time    4.645594
241                                          avg_poi_cnt    4.634572
249                                  poi_info_time_ratio    4.601846
255                                   poi_list_cnt_ratio    4.599931
184                                      is_mid_distance    4.597707
110                                            is_budget    4.577580
29                                             star2_cnt    4.574765
11                                       search_page_cnt    4.574452
15                                          poi_info_cnt    4.572376
111                                           is_express    4.542310
254                                search_page_cnt_ratio    4.536879
210                                       low_star_ratio    4.499413
239                                         avg_city_cnt    4.494834
172          is_holiday_weekend_vacation_sameday_booking    4.490098
75                                              dorm_cnt    4.482160
161                                          session_cnt    4.466584
7                                                poi_cnt    4.450650
10                                             stay_time    4.431890
244                                        avg_order_cnt    4.395975
51                                          lowprice_cnt    4.390692
242                                        avg_goods_cnt    4.381824
26                                            waitou_cnt    4.355641
170                                 is_overnight_booking    4.347057
6                                              goods_cnt    4.327137
153                                       is_triple_room    4.313499
21                                      create_order_cnt    4.264162
259                               create_order_cnt_ratio    4.260229
238                              avg_checkin_datekey_cnt    4.197232
32                                             star5_cnt    4.093219
30                                             star3_cnt    4.078798
236                                     standalone_ratio    3.860868
258                                  room_info_cnt_ratio    3.173000
251                                 room_info_time_ratio    3.102839
182                   is_order_workday_overnight_booking    3.077592
215                                         couple_ratio    2.800245
37                                            couple_cnt    2.751897
19                                         room_info_cnt    2.709677
179  is_order_holiday_weekend_vacation_overnight_booking    2.703470
20                                        room_info_time    2.628637
74                                        standalone_cnt    2.262435
257                                  room_list_cnt_ratio    0.000000
250                                 room_list_time_ratio    0.000000
117                                          is_homestay    0.000000
3                           vacation_checkin_datekey_cnt    0.000000
44                                        guesthouse_cnt    0.000000
222                                     guesthouse_ratio    0.000000
189                             is_order_nearby_distance    0.000000
188                                is_order_mid_distance    0.000000
187                               is_order_long_distance    0.000000
155                                        is_standalone    0.000000
17                                         room_list_cnt    0.000000
104                                          is_vacation    0.000000
18                                        room_list_time    0.000000
126                                            is_scarce    0.000000
124                                            is_family    0.000000
123                                             is_villa    0.000000
122                                      is_resort_hotel    0.000000
190                              is_order_short_distance    0.000000

In [32]:
xgbm.save_model('xgb_intention_model_v2.json')
joblib.dump(iso,'xgb_intention_model_v2_iso.pkl')
with open('xgb_intention_model_v2.txt.meta', 'w') as f:
    json.dump({'best_threshold': best_threshold}, f)

In [7]:
lgbm = lgb.Booster(model_file='lgb_intention_model_v2.txt')
iso_lgbm = joblib.load('lgb_intention_model_v2_iso.pkl')
with open('lgb_intention_model_v2.txt.meta', 'r') as f:
    meta = json.load(f)
best_threshold_lgbm = meta['best_threshold']

In [8]:
xgbm = xgb.Booster(model_file='xgb_intention_model_v2.json')
iso_xgbm = joblib.load('xgb_intention_model_v2_iso.pkl')
with open('xgb_intention_model_v2.txt.meta', 'r') as f:
    meta = json.load(f)
best_threshold_xgbm = meta['best_threshold']

In [18]:
lgb_prob_raw = lgbm.predict(X_test)
lgb_prob_cal = iso_lgbm.transform(lgb_prob_raw)

dtest = xgb.DMatrix(X_test)
xgb_prob_raw = xgbm.predict(dtest)
xgb_prob_cal = iso_xgbm.transform(xgb_prob_raw)

print("LGBM Raw AUC:",roc_auc_score(y_test,lgb_prob_raw))
print("LGBM Cal AUC:",roc_auc_score(y_test,lgb_prob_cal))
print("XGB Raw AUC:",roc_auc_score(y_test,xgb_prob_raw))
print("XGB Cal AUC:",roc_auc_score(y_test,xgb_prob_cal))

best_threshold = 0.5
best_acc = 0
best_weight = 0

for w in np.arange(0,1.01,0.05):
    ensemble_prob = w*lgb_prob_cal+(1-w)*xgb_prob_cal
    for t in np.arange(0.1,0.91,0.01):
        pred = (ensemble_prob>=t).astype(int)
        acc = accuracy_score(y_test,pred)
        if acc > best_acc:
            best_acc = acc
            best_weight = w
            best_threshold = t

y_pred = (ensemble_prob >= best_threshold).astype(int)

print("Best weight:",best_weight)
print("Best threshold:",best_threshold)
print("Best Accuracy:",best_acc)
print("AUC:",roc_auc_score(y_test,ensemble_prob))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

LGBM Raw AUC: 0.9210823368607524
LGBM Cal AUC: 0.9218444406386397
XGB Raw AUC: 0.9637207470045431
XGB Cal AUC: 0.9635148046544992
Best weight: 0.0
Best threshold: 0.5299999999999998
Best Accuracy: 0.9009202623023089
AUC: 0.9218444406386397
              precision    recall  f1-score   support

           0       0.81      0.84      0.82      7983
           1       0.87      0.84      0.86     10164

    accuracy                           0.84     18147
   macro avg       0.84      0.84      0.84     18147
weighted avg       0.84      0.84      0.84     18147

[[6740 1243]
 [1631 8533]]

In [21]:
ensemble_meta = {
    "lgb_weight": float(best_weight),
    "xgb_weight": float(1-best_weight),
    "best_threshold": float(best_threshold)
}
with open('lgb_xgb_ensemble.meta', 'w') as f:
    json.dump(ensemble_meta, f)

In [23]:
with open('lgb_xgb_ensemble.meta','r') as f:
    ensemble_meta = json.load(f)
lgb_weight = ensemble_meta['lgb_weight']
xgb_weight = ensemble_meta['xgb_weight']
best_threshold_ensemble = ensemble_meta['best_threshold']

In [7]:
%%sql rela --preview --quiet

select *
from mart_jiulv_flow.dim_stp_session_rel_df

                                             session_id                                    related_session_id        dt level3_biz_code
0  09134BB6-4A1B-4B55-BF39-6FC24963369A1759568750251996  09134BB6-4A1B-4B55-BF39-6FC24963369A1759240160230285  20251004           hotel
1  340fd86c-afd9-4f08-ac51-33c5e788f6df1759569819029113  340fd86c-afd9-4f08-ac51-33c5e788f6df1759569867084794  20251004           hotel
2  e4583023-7353-4a2d-b63f-b8f5772631961759580732708635  e4583023-7353-4a2d-b63f-b8f5772631961759592447843438  20251004           hotel
3  e4583023-7353-4a2d-b63f-b8f5772631961759542335064572  e4583023-7353-4a2d-b63f-b8f5772631961759402462675148  20251004           hotel
4  e4583023-7353-4a2d-b63f-b8f5772631961759592447843438  e4583023-7353-4a2d-b63f-b8f5772631961759572593514300  20251004           hotel
5  BB8F1820-EDE7-4617-A5B5-EEF6D96211531759547394045762  BB8F1820-EDE7-4617-A5B5-EEF6D96211531758126235462625  20251004           hotel
6   cf8bd27c-c47e-4c1e-bab9-443ec25e43d0175956079034534  cf8bd27c-c47e-4c1e-bab9-443ec25e43d01759200230462139  20251004           hotel
7  0F31630D-3C6C-4273-B789-C0E90F3CAB9F1759568839516957  0F31630D-3C6C-4273-B789-C0E90F3CAB9F1759467434164221  20251004           hotel
8  F78CD230-0C2D-4C8A-8DE0-92F7F81351121759581010198480  F78CD230-0C2D-4C8A-8DE0-92F7F81351121759469257143786  20251004           hotel
9  1F1BBB0F-3115-4AC7-B2D4-01D958A9D5C51759584183046697  1F1BBB0F-3115-4AC7-B2D4-01D958A9D5C51759582865801925  20251004           hotel

In [8]:
%%sql test --preview --quiet

select 
    a.*,
    b.survey_intention,
    b.survey_type
from mart_jiulv_flow.dws_stp_session_comp_df a
join mart_hoteldim.stp_survey_result b
on a.session_id = b.session_id

/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series
/opt/meituan/spark-3.0/python/pyspark/sql/pandas/conversion.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column_name] = series

                                             session_id  holiday_weekend_vacation_checkin_datekey_cnt  holiday_checkin_datekey_cnt  weekend_checkin_datekey_cnt  vacation_checkin_datekey_cnt  lead_time  checkin_datekey_cnt  goods_cnt  poi_cnt  aoi_cnt  city_cnt  stay_time  search_page_cnt  search_page_time  poi_list_cnt  poi_list_time  poi_info_cnt  poi_info_time  room_list_cnt  room_list_time  room_info_cnt  room_info_time  create_order_cnt  create_order_time  evaluate_page_cnt  evaluate_page_time  search_scenic_cnt  waitou_cnt  rednote_cnt  order_cnt  star2_cnt  star3_cnt  star4_cnt  star5_cnt  budget_cnt  express_cnt  business_cnt  theme_cnt  couple_cnt  apartment_cnt  inn_cnt  homestay_cnt  hostel_cnt  farmstay_cnt  family_guesthouse_cnt  guesthouse_cnt  resort_hotel_cnt  villa_cnt  family_cnt  esports_cnt  scarce_cnt  unique_cnt  lowprice_cnt  good_cnt  tourism_core_city_cnt  tourism_big_city_cnt  tourism_seasonal_city_cnt  tier1_city_cnt  new_tier1_city_cnt  tier2_city_cnt  tier3_city_cnt  tier4_city_cnt  tier5_city_cnt  university_cnt  transportation_hub_cnt  scenic_area_cnt  hospital_cnt  performance_sports_venue_cnt  convention_center_cnt  industrial_park_cnt  king_room_cnt  single_room_cnt  double_room_cnt  triple_room_cnt  suite_cnt  standalone_cnt  dorm_cnt  is_college_student  is_adult_single  is_adult_married_no_kids  is_adult_married_with_kids  is_over_60  is_senior  is_middle_age  is_young  is_minor  is_high_value  is_mid_value  is_low_value  is_l4  is_l1_3  is_youth_campus  is_business_elite  is_self_social  is_practical_life  is_family_guardian  is_vital_soldier  is_quality_visitor  is_kid_explorer  is_occasional_traveler  holiday_rnt_pct  travel_distance  is_holiday_weekend_vacation  is_holiday  is_weekend  is_vacation  order_lead_time  is_star2  is_star3  is_star4  is_star5  is_budget  is_express  is_business  is_theme  is_couple  is_apartment  is_inn  is_homestay  is_hostel  is_farmstay  is_family_guesthouse  is_guesthouse  is_resort_hotel  is_villa  is_family  is_esports  is_scarce  is_unique  is_lowprice  is_good  order_travel_distance  is_search_scenic  is_waitou  is_rednote  is_tourism_core_city  is_tourism_big_city  is_tourism_seasonal_city  is_tier1_city  is_new_tier1_city  is_tier2_city  is_tier3_city  is_tier4_city  is_tier5_city  is_university  is_transportation_hub  is_scenic_area  is_hospital  is_performance_sports_venue  is_convention_center  is_industrial_park  is_king_room  is_single_room  is_double_room  is_triple_room  is_suite  is_standalone  is_dorm  search_cnt  travel_session_cnt  is_search  is_travel_session  session_cnt  event_cnt  advance_checkin_datekey_cnt  sameday_checkin_datekey_cnt  overnight_checkin_datekey_cnt        dt
0  68c42742-3fd9-4c37-86cc-fcba1c3a87cf1780194675671856                                             2                            0                            2                             0   0.000000                    4          1        1        1         1     38.679                0             0.000             0          0.000             9         20.859              0             0.0              0           0.000                12             15.407                  0                 0.0                  0           0            0         13         22          0          0          0           0            0             0          0           0              0        0             0           0             0                      0               0                 0          0           0            0           0           0             0         0                      0                    22                          0               0                  22               0               0               0               0              22                       0                0             0                            22                      0                    0              0                0                0                0          0               0        13                   0                0                         0                           0           0          0              0         0         0              1             0             1      1        1                0                  0               0                  0                   0                 0                   0                0                       0         0.074456         0.014047                            1           0           1            0         0.000000         0         0         0         1          0           0            0         0          0             0       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 0          0           0                     0                    1                         0              0                  1              0              0              0              0              1                      0               0            0                            1                     0                   0             0               0               0               0         0              0        1           0                   0          0                  0            5         22                            0                            4                              0  20260531
1  87765f99-0d3a-4b88-ac43-98c13d9e833a1780193754337666                                             0                            0                            0                             0   0.000000                    1          2        2        1         1    145.249                0             0.000             0          0.000            11         77.323              0             0.0              0           0.000                 9             33.267                  0                 0.0                  0           0            0          4          0          0         19          0           0            0            19          0           0              0        0             0           0             0                      0               0                 0          0           0            0           0          19             0        19                      0                    19                          0               0                   0               0              19               0               0               0                       0                0            19                             0                      0                    0              8                0                0                0          0               0         0                   0                0                         0                           1           0          0              0         1         0              1             0             0      1        0                0                  0               0                  0                   1                 0                   0                0                       0         0.050000         2.095808                            0           0           0            0         0.000000         0         0         0         0          0           1            0         0          0             1       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    1.0                 0          1           2                     0                    1                         0              0                  0              0              1              0              0              0                      0               0            1                            0                     0                   0             1               0               0               0         0              0        0           0                   0          0                  0            2         24                            0                            1                              0  20260531
2  1a6eac45-99b5-4e06-ac73-9d8fcd9506351777862734723889                                             1                            1                            0                             0   0.000000                    1          8        9        3         1   1499.223                0             0.000            12        291.440            39        542.794              0             0.0              0           0.000                 2             15.525                  0                 0.0                  0           0            0          6         62          0          0          0           8           48             6          0           0              0        0             0           0             0                      0               0                 0          0           9            1           0           8            54        62                     62                     0                          0               0                   0               0               0              62               0               0                      53               53             1                             0                      0                    0              1                0               18                0          0               0         0                   0                0                         1                           0           0          0              0         1         0              0             1             0      0        1                0                  0               0                  0                   0                 0                   0                0                       1         0.250000       366.846113                            1           1           0            0         0.000000         0         0         0         1          0           0            0         0          1             0       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 1          1         367                     1                    0                         0              0                  0              0              0              1              0              0                      1               1            0                            0                     0                   0             0               0               1               0         0              0        0          41                  82          1                  1            3         89                            0                            1                              0  20260504
3   86e0b3a0-f7cb-411c-aa52-e15f38871a13177737951388742                                             0                            0                            0                             0   0.000000                    1          1        2        1         1    205.266                1             8.755             5         15.172             5         36.617              0             0.0              0           0.000                 6             80.261                  0                 0.0                  0           0            0          5          0         10          0          0           0            0            10          0           0              0        0             0           0             0                      0               0                 0          0           0            0           0           0             0         0                      0                     0                          0               0                   0              10               0               0               0              10                       0                0             0                             0                      0                    0              5                0                0                0          0               0         0                   0                1                         0                           0           0          0              0         0         1              0             1             0      0        1                0                  0               0                  0                   0                 0                   0                0                       1         0.000000       252.737156                            0           0           0            0         0.000000         0         0         0         0          1           0            0         0          0             1       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 0          0         252                     0                    0                         0              0                  0              1              0              0              0              1                      0               0            0                            0                     0                   0             1               0               0               0         0              0        0           6                   0          1                  0            1         25                            0                            1                              0  20260428
4  17EA6D3A-6DCC-47F6-9855-0BB18CFF72FF1776737728094687                                             1                            0                            1                             0   3.900826                    2          7       22        1         1    622.857                4            31.870            40        200.773            51        199.994              0             0.0              0           0.000                 6             58.917                  0                 0.0                  0           3            0          8         77          0          0          0          29            0            10         16           0              5        0             6           0             0                      0               0                 0          0           0           17           0           3            62        65                      0                    77                          0               0                  77               0               0               0               0              77                       0                0            77                            77                      0                    0             24                0                0                0          0               0         0                   0                1                         0                           0           0          0              0         1         0              1             1             0      1        1                0                  0               1                  0                   0                 0                   0                0                       1         0.000000        75.140136                            1           0           1            0         4.000000         0         0         0         1          0           0            0         1          0             0       1            0          0            0                     0              0                0         0          0           0          0          0            1        0                    0.0                 1          1          75                     0                    1                         0              0                  1              0              0              0              0              1                      0               0            1                            1                     0                   0             1               0               0               0         0              0        0           0                   0          0                  0            3        133                            1                            1                              0  20260421
5                            19e6e75b55c-6304-a028-497a                                             0                            0                            0                             0   0.000000                    1          1        2        1         1     56.975                0             0.000             0          0.000             2         12.495              0             0.0              0           0.000                 2             42.461                  0                 0.0                  0           0            0          2          4          0          0          0           4            0             0          0           0              0        0             0           0             0                      0               0                 0          0           0            0           0           0             4         4                      0                     4                          0               4                   0               0               0               0               0               4                       0                4             4                             0                      0                    4              2                0                0                0          0               0         0                   0                1                         0                           0           0          0              0         1         0              0             1             0      0        1                0                  0               0                  0                   0                 0                   0                0                       1         0.000000       517.340317                            0           0           0            0         0.000000         0         0         0         1          0           0            0         1          0             0       0            0          0            0                     0              0                0         0          0           0          0          0            0        0                    0.0                 1          1         517                     0                    1                         0              1                  0              0              0              0              0              1                      0               1            1                            0                     0                   1             1               0               0               0         0              0        0           0                   0          0                  0            2          5                            0                            1                              0  20260528

In [ ]:
test = metrics(test).toPandas()

In [5]:
# test.to_parquet("hdfs:///user/luyiwei03/stp_test.parquet", index=False)
test = pd.read_parquet("hdfs:///user/luyiwei03/stp_test.parquet")

In [6]:
test = test[test['survey_type']=='访谈']

In [10]:
X = test.drop(columns=['intention','session_id','dt','survey_intention','survey_type','level3_biz_code'], errors='ignore')
y_pred_prob_raw = lgbm.predict(X)
y_pred_prob = iso_lgbm.transform(y_pred_prob_raw)
y_pred = (y_pred_prob >= best_threshold_lgbm).astype(int)
y_true = test['survey_intention']

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.7011494252873564
              precision    recall  f1-score   support

           0       0.66      0.72      0.69        40
           1       0.74      0.68      0.71        47

    accuracy                           0.70        87
   macro avg       0.70      0.70      0.70        87
weighted avg       0.71      0.70      0.70        87

In [12]:
X = test.drop(columns=['intention','session_id','dt','survey_intention','survey_type','level3_biz_code'], errors='ignore')
dtest = xgb.DMatrix(X)
y_pred_prob_raw = xgbm.predict(dtest)
y_pred_prob = iso_xgbm.transform(y_pred_prob_raw)
y_pred = (y_pred_prob >= best_threshold_xgbm).astype(int)
y_true = test['survey_intention']

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.6781609195402298
              precision    recall  f1-score   support

           0       0.64      0.68      0.66        40
           1       0.71      0.68      0.70        47

    accuracy                           0.68        87
   macro avg       0.68      0.68      0.68        87
weighted avg       0.68      0.68      0.68        87

In [27]:
X = test.drop(columns=['intention','session_id','dt','survey_intention','survey_type','level3_biz_code'], errors='ignore')
dtest = xgb.DMatrix(X)
lgb_prob_raw = lgbm.predict(X)
lgb_prob_cal = iso_lgbm.transform(lgb_prob_raw)
dtest = xgb.DMatrix(X)
xgb_prob_raw = xgbm.predict(dtest)
xgb_prob_cal = iso_xgbm.transform(xgb_prob_raw)

ensemble_prob = lgb_weight*lgb_prob_cal + xgb_weight*xgb_prob_cal
y_pred = (ensemble_prob >= best_threshold_ensemble).astype(int)
y_true = test['survey_intention']

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))

Accuracy: 0.6781609195402298
              precision    recall  f1-score   support

           0       0.64      0.68      0.66        40
           1       0.71      0.68      0.70        47

    accuracy                           0.68        87
   macro avg       0.68      0.68      0.68        87
weighted avg       0.68      0.68      0.68        87